version: '3'

services:
  app:
    build:
      context: .
    container_name: next-boilerplate
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
